### ISSUE TITLE
AttributeError: 'ClientOptions' object has no attribute 'api_audience'; `google-cloud-core==2.2.3` is incompatible with `google-api-core==2.8.2`

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/python-cloud-core#208]
It ;looks like `google-cloud-core==2.2.3` is incompatible with `google-api-core==2.8.2`
```
AttributeError: 'ClientOptions' object has no attribute 'api_audience'
```
`google-cloud-core==2.3.0` seems to be compatible.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-cloud-core/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: 3.7
  - pip version: `pip --version`
  - `google-cloud-core` version: 2.2.3

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vam-google** [comment]
@atulep Can you please take a look? Looks like this change made it incompatible: https://github.com/googleapis/python-api-core/pull/379

On the other hand, given our development workflow, since 2.3.0 works with latest version of google-api-core we would just recommend using that version or newer.

Also, can you please provide full stack trace on where exactly api_audience is being used in older version of  google-cloud-core? Checking the diff of 2.2.3 and 2.3.0 (https://github.com/googleapis/python-cloud-core/compare/v2.2.3...v2.3.0) I can't spot a relevant difference.

**Comment by Ark-kun** [comment]
I lost the stack trace initially.

But now I've managed to recover it and I see that this issue is in another library - `google-cloud-aiplatform`
I apologize for the confusion.
```
/tmp/ipykernel_16859/1666459801.py in <module>
     54 if __name__ == '__main__':
     55     from google.cloud import aiplatform
---> 56     aiplatform.PipelineJob.from_pipeline_func(pipeline_func=pipeline_func).submit()

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/pipeline_jobs.py in submit(self, service_account, network, create_request_timeout, experiment)
    360         _LOGGER.log_create_with_lro(self.__class__)
    361 
--> 362         self._gca_resource = self.api_client.create_pipeline_job(
    363             parent=self._parent,
    364             pipeline_job=self._gca_resource,

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/utils/__init__.py in __getattr__(self, name)
    423     def __getattr__(self, name: str) -> Any:
    424         """Instantiates client and returns attribute of the client."""
--> 425         return getattr(self._clients[self._default_version], name)
    426 
    427     def select_version(self, version: str) -> VertexAiServiceClient:

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/utils/__init__.py in __getattr__(self, name)
    357                 credentials=self._credentials,
    358                 client_options=self._client_options,
--> 359                 client_info=self._client_info,
    360             )
    361             return getattr(temporary_client, name)

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform_v1/services/pipeline_service/client.py in __init__(self, credentials, transport, client_options, client_info)
    626                 client_info=client_info,
    627                 always_use_jwt_access=True,
--> 628                 api_audience=client_options.api_audience,
    629             )
    630 

AttributeError: 'ClientOptions' object has no attribute 'api_audience'
```

The issue was introduced by https://github.com/googleapis/python-aiplatform/pull/1454 and https://github.com/googleapis/googleapis/commit/23f1a157189581734c7a77cddfeb7c5bc1e440ae

**Comment by Ark-kun** [comment]
Hmm. It looks like aiplatform package already states it's not compatible with 2.2.*

https://github.com/googleapis/python-cloud-core/blob/c194fc4caf7f3014e77563cbc123ea74014ded8b/setup.py#L31
